# Generated by Django 5.2.1 on 2025-05-24 17:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="transaction_pin",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Code PIN de transaction",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="kyc_photo_id",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="kyc/",
                verbose_name="Photo de la pièce d'identité",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="kyc_selfie",
            field=models.ImageField(
                blank=True, null=True, upload_to="kyc/", verbose_name="Selfie KYC"
            ),
        ),
        migrations.CreateModel(
            name="ReferralCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=20,
                        unique=True,
                        verbose_name="Code de parrainage",
                    ),
                ),
                (
                    "bonus_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=10,
                        verbose_name="Montant du bonus",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "referrer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_code",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Parrain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code de Parrainage",
                "verbose_name_plural": "Codes de Parrainage",
            },
        ),
    ]
