# Generated by Django 5.2.1 on 2025-05-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountcode",
            name="code",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Code de réduction"
            ),
        ),
    ]
