# Generated by Django 5.2.1 on 2025-05-24 17:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_alter_discountcode_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("send", "Envoi"),
                    ("receive", "Réception"),
                    ("withdrawal", "Retrait"),
                    ("deposit", "Dépôt"),
                ],
                default="send",
                max_length=20,
                verbose_name="Type de transaction",
            ),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="code",
            field=models.CharField(
                default=uuid.uuid4,
                max_length=40,
                unique=True,
                verbose_name="Code de réduction",
            ),
        ),
    ]
