# Generated by Django 5.2.1 on 2025-05-24 18:29

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_transaction_transaction_type_alter_discountcode_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.RemoveField(
            model_name="discountcode",
            name="description",
        ),
        migrations.AddField(
            model_name="discountcode",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de Création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de Mise à Jour"
            ),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="code",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Code de Réduction"
            ),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_discount_codes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="discount_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Pourcentage de Réduction",
            ),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="fixed_amount_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Montant Fixe de Réduction",
            ),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="max_uses",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Nombre Maximum d'Utilisations"
            ),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="uses_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Nombre d'Utilisations Actuelles"
            ),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="valid_from",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Valide à partir de"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Montant Initial"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de Création"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="final_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="Montant Final (après frais/réductions)",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="receiver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Bénéficiaire",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Expéditeur",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("reversed", "Reversed"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("send", "Send Money"),
                    ("receive", "Receive Money"),
                    ("withdrawal", "Withdrawal"),
                    ("recharge", "Recharge/Deposit"),
                ],
                max_length=10,
                verbose_name="Type de Transaction",
            ),
        ),
    ]
