# Generated by Django 5.2.1 on 2025-05-24 18:35

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0002_alter_wallet_options_alter_wallet_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de Création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wallet",
            name="currency",
            field=models.CharField(default="XAF", max_length=5, verbose_name="Devise"),
        ),
        migrations.AddField(
            model_name="wallet",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de Mise à Jour"
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="Solde",
            ),
        ),
    ]
