# Generated by Django 5.2.1 on 2025-05-24 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "wallets",
            "0003_wallet_created_at_wallet_currency_wallet_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="currency",
        ),
    ]
