# Generated by Django 5.2.1 on 2025-05-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0004_remove_wallet_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="currency",
            field=models.CharField(
                choices=[
                    ("XOF", "Franc CFA BCEAO (Togo, Bénin, Burkina Faso, etc.)"),
                    ("XAF", "Franc CFA BEAC (Cameroun, Tchad, Centrafrique, etc.)"),
                ],
                default="XOF",
                max_length=3,
                verbose_name="Devise du portefeuille",
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Dernière Mise à Jour"
            ),
        ),
    ]
